/**
 * SellPass.WebApi
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The BulkPaymentMethodsUpdate model module.
 * @module model/BulkPaymentMethodsUpdate
 * @version v1
 */
class BulkPaymentMethodsUpdate {
    /**
     * Constructs a new <code>BulkPaymentMethodsUpdate</code>.
     * @alias module:model/BulkPaymentMethodsUpdate
     */
    constructor() { 
        
        BulkPaymentMethodsUpdate.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>BulkPaymentMethodsUpdate</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/BulkPaymentMethodsUpdate} obj Optional instance to populate.
     * @return {module:model/BulkPaymentMethodsUpdate} The populated <code>BulkPaymentMethodsUpdate</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new BulkPaymentMethodsUpdate();

            if (data.hasOwnProperty('productIds')) {
                obj['productIds'] = ApiClient.convertToType(data['productIds'], ['Number']);
            }
            if (data.hasOwnProperty('gatewaysList')) {
                obj['gatewaysList'] = ApiClient.convertToType(data['gatewaysList'], {'String': 'Boolean'});
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>BulkPaymentMethodsUpdate</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>BulkPaymentMethodsUpdate</code>.
     */
    static validateJSON(data) {
        // ensure the json data is an array
        if (!Array.isArray(data['productIds'])) {
            throw new Error("Expected the field `productIds` to be an array in the JSON data but got " + data['productIds']);
        }

        return true;
    }


}



/**
 * @member {Array.<Number>} productIds
 */
BulkPaymentMethodsUpdate.prototype['productIds'] = undefined;

/**
 * @member {Object.<String, Boolean>} gatewaysList
 */
BulkPaymentMethodsUpdate.prototype['gatewaysList'] = undefined;






export default BulkPaymentMethodsUpdate;

