/**
 * SellPass.WebApi
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The BulkVisibilityUpdate model module.
 * @module model/BulkVisibilityUpdate
 * @version v1
 */
class BulkVisibilityUpdate {
    /**
     * Constructs a new <code>BulkVisibilityUpdate</code>.
     * @alias module:model/BulkVisibilityUpdate
     */
    constructor() { 
        
        BulkVisibilityUpdate.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>BulkVisibilityUpdate</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/BulkVisibilityUpdate} obj Optional instance to populate.
     * @return {module:model/BulkVisibilityUpdate} The populated <code>BulkVisibilityUpdate</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new BulkVisibilityUpdate();

            if (data.hasOwnProperty('productIds')) {
                obj['productIds'] = ApiClient.convertToType(data['productIds'], ['Number']);
            }
            if (data.hasOwnProperty('unlisted')) {
                obj['unlisted'] = ApiClient.convertToType(data['unlisted'], 'Boolean');
            }
            if (data.hasOwnProperty('private')) {
                obj['private'] = ApiClient.convertToType(data['private'], 'Boolean');
            }
            if (data.hasOwnProperty('onHold')) {
                obj['onHold'] = ApiClient.convertToType(data['onHold'], 'Boolean');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>BulkVisibilityUpdate</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>BulkVisibilityUpdate</code>.
     */
    static validateJSON(data) {
        // ensure the json data is an array
        if (!Array.isArray(data['productIds'])) {
            throw new Error("Expected the field `productIds` to be an array in the JSON data but got " + data['productIds']);
        }

        return true;
    }


}



/**
 * @member {Array.<Number>} productIds
 */
BulkVisibilityUpdate.prototype['productIds'] = undefined;

/**
 * @member {Boolean} unlisted
 */
BulkVisibilityUpdate.prototype['unlisted'] = undefined;

/**
 * @member {Boolean} private
 */
BulkVisibilityUpdate.prototype['private'] = undefined;

/**
 * @member {Boolean} onHold
 */
BulkVisibilityUpdate.prototype['onHold'] = undefined;






export default BulkVisibilityUpdate;

