/**
 * SellPass.WebApi
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import GatewayRules from './GatewayRules';

/**
 * The ChangePayPalFFRequest model module.
 * @module model/ChangePayPalFFRequest
 * @version v1
 */
class ChangePayPalFFRequest {
    /**
     * Constructs a new <code>ChangePayPalFFRequest</code>.
     * @alias module:model/ChangePayPalFFRequest
     */
    constructor() { 
        
        ChangePayPalFFRequest.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>ChangePayPalFFRequest</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/ChangePayPalFFRequest} obj Optional instance to populate.
     * @return {module:model/ChangePayPalFFRequest} The populated <code>ChangePayPalFFRequest</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ChangePayPalFFRequest();

            if (data.hasOwnProperty('email')) {
                obj['email'] = ApiClient.convertToType(data['email'], 'String');
            }
            if (data.hasOwnProperty('gatewayRules')) {
                obj['gatewayRules'] = GatewayRules.constructFromObject(data['gatewayRules']);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>ChangePayPalFFRequest</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>ChangePayPalFFRequest</code>.
     */
    static validateJSON(data) {
        // ensure the json data is a string
        if (data['email'] && !(typeof data['email'] === 'string' || data['email'] instanceof String)) {
            throw new Error("Expected the field `email` to be a primitive type in the JSON string but got " + data['email']);
        }
        // validate the optional field `gatewayRules`
        if (data['gatewayRules']) { // data not null
          GatewayRules.validateJSON(data['gatewayRules']);
        }

        return true;
    }


}



/**
 * @member {String} email
 */
ChangePayPalFFRequest.prototype['email'] = undefined;

/**
 * @member {module:model/GatewayRules} gatewayRules
 */
ChangePayPalFFRequest.prototype['gatewayRules'] = undefined;






export default ChangePayPalFFRequest;

