/**
 * SellPass.WebApi
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The ChangeStorefrontText model module.
 * @module model/ChangeStorefrontText
 * @version v1
 */
class ChangeStorefrontText {
    /**
     * Constructs a new <code>ChangeStorefrontText</code>.
     * @alias module:model/ChangeStorefrontText
     */
    constructor() { 
        
        ChangeStorefrontText.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>ChangeStorefrontText</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/ChangeStorefrontText} obj Optional instance to populate.
     * @return {module:model/ChangeStorefrontText} The populated <code>ChangeStorefrontText</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ChangeStorefrontText();

            if (data.hasOwnProperty('title')) {
                obj['title'] = ApiClient.convertToType(data['title'], 'String');
            }
            if (data.hasOwnProperty('description')) {
                obj['description'] = ApiClient.convertToType(data['description'], 'String');
            }
            if (data.hasOwnProperty('buttonText')) {
                obj['buttonText'] = ApiClient.convertToType(data['buttonText'], 'String');
            }
            if (data.hasOwnProperty('disableButton')) {
                obj['disableButton'] = ApiClient.convertToType(data['disableButton'], 'Boolean');
            }
            if (data.hasOwnProperty('disableTitle')) {
                obj['disableTitle'] = ApiClient.convertToType(data['disableTitle'], 'Boolean');
            }
            if (data.hasOwnProperty('disableDescription')) {
                obj['disableDescription'] = ApiClient.convertToType(data['disableDescription'], 'Boolean');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>ChangeStorefrontText</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>ChangeStorefrontText</code>.
     */
    static validateJSON(data) {
        // ensure the json data is a string
        if (data['title'] && !(typeof data['title'] === 'string' || data['title'] instanceof String)) {
            throw new Error("Expected the field `title` to be a primitive type in the JSON string but got " + data['title']);
        }
        // ensure the json data is a string
        if (data['description'] && !(typeof data['description'] === 'string' || data['description'] instanceof String)) {
            throw new Error("Expected the field `description` to be a primitive type in the JSON string but got " + data['description']);
        }
        // ensure the json data is a string
        if (data['buttonText'] && !(typeof data['buttonText'] === 'string' || data['buttonText'] instanceof String)) {
            throw new Error("Expected the field `buttonText` to be a primitive type in the JSON string but got " + data['buttonText']);
        }

        return true;
    }


}



/**
 * @member {String} title
 */
ChangeStorefrontText.prototype['title'] = undefined;

/**
 * @member {String} description
 */
ChangeStorefrontText.prototype['description'] = undefined;

/**
 * @member {String} buttonText
 */
ChangeStorefrontText.prototype['buttonText'] = undefined;

/**
 * @member {Boolean} disableButton
 */
ChangeStorefrontText.prototype['disableButton'] = undefined;

/**
 * @member {Boolean} disableTitle
 */
ChangeStorefrontText.prototype['disableTitle'] = undefined;

/**
 * @member {Boolean} disableDescription
 */
ChangeStorefrontText.prototype['disableDescription'] = undefined;






export default ChangeStorefrontText;

