/**
 * SellPass.WebApi
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import GatewayRules from './GatewayRules';

/**
 * The ChangeStripeConnectRequest model module.
 * @module model/ChangeStripeConnectRequest
 * @version v1
 */
class ChangeStripeConnectRequest {
    /**
     * Constructs a new <code>ChangeStripeConnectRequest</code>.
     * @alias module:model/ChangeStripeConnectRequest
     * @param code {String} 
     * @param gatewayRules {module:model/GatewayRules} 
     */
    constructor(code, gatewayRules) { 
        
        ChangeStripeConnectRequest.initialize(this, code, gatewayRules);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, code, gatewayRules) { 
        obj['code'] = code;
        obj['gatewayRules'] = gatewayRules;
    }

    /**
     * Constructs a <code>ChangeStripeConnectRequest</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/ChangeStripeConnectRequest} obj Optional instance to populate.
     * @return {module:model/ChangeStripeConnectRequest} The populated <code>ChangeStripeConnectRequest</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ChangeStripeConnectRequest();

            if (data.hasOwnProperty('code')) {
                obj['code'] = ApiClient.convertToType(data['code'], 'String');
            }
            if (data.hasOwnProperty('gatewayRules')) {
                obj['gatewayRules'] = GatewayRules.constructFromObject(data['gatewayRules']);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>ChangeStripeConnectRequest</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>ChangeStripeConnectRequest</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of ChangeStripeConnectRequest.RequiredProperties) {
            if (!data[property]) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['code'] && !(typeof data['code'] === 'string' || data['code'] instanceof String)) {
            throw new Error("Expected the field `code` to be a primitive type in the JSON string but got " + data['code']);
        }
        // validate the optional field `gatewayRules`
        if (data['gatewayRules']) { // data not null
          GatewayRules.validateJSON(data['gatewayRules']);
        }

        return true;
    }


}

ChangeStripeConnectRequest.RequiredProperties = ["code", "gatewayRules"];

/**
 * @member {String} code
 */
ChangeStripeConnectRequest.prototype['code'] = undefined;

/**
 * @member {module:model/GatewayRules} gatewayRules
 */
ChangeStripeConnectRequest.prototype['gatewayRules'] = undefined;






export default ChangeStripeConnectRequest;

