/**
 * SellPass.WebApi
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The ChangeShopCurrencyRequest model module.
 * @module model/ChangeShopCurrencyRequest
 * @version v1
 */
class ChangeShopCurrencyRequest {
    /**
     * Constructs a new <code>ChangeShopCurrencyRequest</code>.
     * @alias module:model/ChangeShopCurrencyRequest
     * @param currency {String} 
     */
    constructor(currency) { 
        
        ChangeShopCurrencyRequest.initialize(this, currency);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, currency) { 
        obj['currency'] = currency;
    }

    /**
     * Constructs a <code>ChangeShopCurrencyRequest</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/ChangeShopCurrencyRequest} obj Optional instance to populate.
     * @return {module:model/ChangeShopCurrencyRequest} The populated <code>ChangeShopCurrencyRequest</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ChangeShopCurrencyRequest();

            if (data.hasOwnProperty('currency')) {
                obj['currency'] = ApiClient.convertToType(data['currency'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>ChangeShopCurrencyRequest</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>ChangeShopCurrencyRequest</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of ChangeShopCurrencyRequest.RequiredProperties) {
            if (!data[property]) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['currency'] && !(typeof data['currency'] === 'string' || data['currency'] instanceof String)) {
            throw new Error("Expected the field `currency` to be a primitive type in the JSON string but got " + data['currency']);
        }

        return true;
    }


}

ChangeShopCurrencyRequest.RequiredProperties = ["currency"];

/**
 * @member {String} currency
 */
ChangeShopCurrencyRequest.prototype['currency'] = undefined;






export default ChangeShopCurrencyRequest;

