/**
 * SellPass.WebApi
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The ChangeShopStatusRequest model module.
 * @module model/ChangeShopStatusRequest
 * @version v1
 */
class ChangeShopStatusRequest {
    /**
     * Constructs a new <code>ChangeShopStatusRequest</code>.
     * @alias module:model/ChangeShopStatusRequest
     * @param onHold {Boolean} 
     */
    constructor(onHold) { 
        
        ChangeShopStatusRequest.initialize(this, onHold);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, onHold) { 
        obj['onHold'] = onHold;
    }

    /**
     * Constructs a <code>ChangeShopStatusRequest</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/ChangeShopStatusRequest} obj Optional instance to populate.
     * @return {module:model/ChangeShopStatusRequest} The populated <code>ChangeShopStatusRequest</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ChangeShopStatusRequest();

            if (data.hasOwnProperty('onHold')) {
                obj['onHold'] = ApiClient.convertToType(data['onHold'], 'Boolean');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>ChangeShopStatusRequest</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>ChangeShopStatusRequest</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of ChangeShopStatusRequest.RequiredProperties) {
            if (!data[property]) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }

        return true;
    }


}

ChangeShopStatusRequest.RequiredProperties = ["onHold"];

/**
 * @member {Boolean} onHold
 */
ChangeShopStatusRequest.prototype['onHold'] = undefined;






export default ChangeShopStatusRequest;

