/**
 * SellPass.WebApi
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The CheckCouponRequest model module.
 * @module model/CheckCouponRequest
 * @version v1
 */
class CheckCouponRequest {
    /**
     * Constructs a new <code>CheckCouponRequest</code>.
     * @alias module:model/CheckCouponRequest
     * @param productIds {Array.<Number>} 
     * @param couponName {String} 
     */
    constructor(productIds, couponName) { 
        
        CheckCouponRequest.initialize(this, productIds, couponName);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, productIds, couponName) { 
        obj['productIds'] = productIds;
        obj['couponName'] = couponName;
    }

    /**
     * Constructs a <code>CheckCouponRequest</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/CheckCouponRequest} obj Optional instance to populate.
     * @return {module:model/CheckCouponRequest} The populated <code>CheckCouponRequest</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new CheckCouponRequest();

            if (data.hasOwnProperty('productIds')) {
                obj['productIds'] = ApiClient.convertToType(data['productIds'], ['Number']);
            }
            if (data.hasOwnProperty('couponName')) {
                obj['couponName'] = ApiClient.convertToType(data['couponName'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>CheckCouponRequest</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>CheckCouponRequest</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of CheckCouponRequest.RequiredProperties) {
            if (!data[property]) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is an array
        if (!Array.isArray(data['productIds'])) {
            throw new Error("Expected the field `productIds` to be an array in the JSON data but got " + data['productIds']);
        }
        // ensure the json data is a string
        if (data['couponName'] && !(typeof data['couponName'] === 'string' || data['couponName'] instanceof String)) {
            throw new Error("Expected the field `couponName` to be a primitive type in the JSON string but got " + data['couponName']);
        }

        return true;
    }


}

CheckCouponRequest.RequiredProperties = ["productIds", "couponName"];

/**
 * @member {Array.<Number>} productIds
 */
CheckCouponRequest.prototype['productIds'] = undefined;

/**
 * @member {String} couponName
 */
CheckCouponRequest.prototype['couponName'] = undefined;






export default CheckCouponRequest;

