/**
 * SellPass.WebApi
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The CreateCategoryRequest model module.
 * @module model/CreateCategoryRequest
 * @version v1
 */
class CreateCategoryRequest {
    /**
     * Constructs a new <code>CreateCategoryRequest</code>.
     * @alias module:model/CreateCategoryRequest
     * @param name {String} 
     * @param listingIds {Array.<Number>} 
     */
    constructor(name, listingIds) { 
        
        CreateCategoryRequest.initialize(this, name, listingIds);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, name, listingIds) { 
        obj['name'] = name;
        obj['listingIds'] = listingIds;
    }

    /**
     * Constructs a <code>CreateCategoryRequest</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/CreateCategoryRequest} obj Optional instance to populate.
     * @return {module:model/CreateCategoryRequest} The populated <code>CreateCategoryRequest</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new CreateCategoryRequest();

            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
            if (data.hasOwnProperty('listingIds')) {
                obj['listingIds'] = ApiClient.convertToType(data['listingIds'], ['Number']);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>CreateCategoryRequest</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>CreateCategoryRequest</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of CreateCategoryRequest.RequiredProperties) {
            if (!data[property]) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['name'] && !(typeof data['name'] === 'string' || data['name'] instanceof String)) {
            throw new Error("Expected the field `name` to be a primitive type in the JSON string but got " + data['name']);
        }
        // ensure the json data is an array
        if (!Array.isArray(data['listingIds'])) {
            throw new Error("Expected the field `listingIds` to be an array in the JSON data but got " + data['listingIds']);
        }

        return true;
    }


}

CreateCategoryRequest.RequiredProperties = ["name", "listingIds"];

/**
 * @member {String} name
 */
CreateCategoryRequest.prototype['name'] = undefined;

/**
 * @member {Array.<Number>} listingIds
 */
CreateCategoryRequest.prototype['listingIds'] = undefined;






export default CreateCategoryRequest;

