/**
 * SellPass.WebApi
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The DiscordSocialConnectSettingsForProductRequest model module.
 * @module model/DiscordSocialConnectSettingsForProductRequest
 * @version v1
 */
class DiscordSocialConnectSettingsForProductRequest {
    /**
     * Constructs a new <code>DiscordSocialConnectSettingsForProductRequest</code>.
     * @alias module:model/DiscordSocialConnectSettingsForProductRequest
     * @param enabled {Boolean} 
     * @param required {Boolean} 
     */
    constructor(enabled, required) { 
        
        DiscordSocialConnectSettingsForProductRequest.initialize(this, enabled, required);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, enabled, required) { 
        obj['enabled'] = enabled;
        obj['required'] = required;
    }

    /**
     * Constructs a <code>DiscordSocialConnectSettingsForProductRequest</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/DiscordSocialConnectSettingsForProductRequest} obj Optional instance to populate.
     * @return {module:model/DiscordSocialConnectSettingsForProductRequest} The populated <code>DiscordSocialConnectSettingsForProductRequest</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new DiscordSocialConnectSettingsForProductRequest();

            if (data.hasOwnProperty('enabled')) {
                obj['enabled'] = ApiClient.convertToType(data['enabled'], 'Boolean');
            }
            if (data.hasOwnProperty('required')) {
                obj['required'] = ApiClient.convertToType(data['required'], 'Boolean');
            }
            if (data.hasOwnProperty('guildId')) {
                obj['guildId'] = ApiClient.convertToType(data['guildId'], 'String');
            }
            if (data.hasOwnProperty('roleIds')) {
                obj['roleIds'] = ApiClient.convertToType(data['roleIds'], ['String']);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>DiscordSocialConnectSettingsForProductRequest</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>DiscordSocialConnectSettingsForProductRequest</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of DiscordSocialConnectSettingsForProductRequest.RequiredProperties) {
            if (!data[property]) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['guildId'] && !(typeof data['guildId'] === 'string' || data['guildId'] instanceof String)) {
            throw new Error("Expected the field `guildId` to be a primitive type in the JSON string but got " + data['guildId']);
        }
        // ensure the json data is an array
        if (!Array.isArray(data['roleIds'])) {
            throw new Error("Expected the field `roleIds` to be an array in the JSON data but got " + data['roleIds']);
        }

        return true;
    }


}

DiscordSocialConnectSettingsForProductRequest.RequiredProperties = ["enabled", "required"];

/**
 * @member {Boolean} enabled
 */
DiscordSocialConnectSettingsForProductRequest.prototype['enabled'] = undefined;

/**
 * @member {Boolean} required
 */
DiscordSocialConnectSettingsForProductRequest.prototype['required'] = undefined;

/**
 * @member {String} guildId
 */
DiscordSocialConnectSettingsForProductRequest.prototype['guildId'] = undefined;

/**
 * @member {Array.<String>} roleIds
 */
DiscordSocialConnectSettingsForProductRequest.prototype['roleIds'] = undefined;






export default DiscordSocialConnectSettingsForProductRequest;

