/**
 * SellPass.WebApi
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The DynamicType model module.
 * @module model/DynamicType
 * @version v1
 */
class DynamicType {
    /**
     * Constructs a new <code>DynamicType</code>.
     * @alias module:model/DynamicType
     */
    constructor() { 
        
        DynamicType.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>DynamicType</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/DynamicType} obj Optional instance to populate.
     * @return {module:model/DynamicType} The populated <code>DynamicType</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new DynamicType();

            if (data.hasOwnProperty('stock')) {
                obj['stock'] = ApiClient.convertToType(data['stock'], 'Number');
            }
            if (data.hasOwnProperty('externalUrl')) {
                obj['externalUrl'] = ApiClient.convertToType(data['externalUrl'], 'String');
            }
            if (data.hasOwnProperty('minAmount')) {
                obj['minAmount'] = ApiClient.convertToType(data['minAmount'], 'Number');
            }
            if (data.hasOwnProperty('maxAmount')) {
                obj['maxAmount'] = ApiClient.convertToType(data['maxAmount'], 'Number');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>DynamicType</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>DynamicType</code>.
     */
    static validateJSON(data) {
        // ensure the json data is a string
        if (data['externalUrl'] && !(typeof data['externalUrl'] === 'string' || data['externalUrl'] instanceof String)) {
            throw new Error("Expected the field `externalUrl` to be a primitive type in the JSON string but got " + data['externalUrl']);
        }

        return true;
    }


}



/**
 * @member {Number} stock
 */
DynamicType.prototype['stock'] = undefined;

/**
 * @member {String} externalUrl
 */
DynamicType.prototype['externalUrl'] = undefined;

/**
 * @member {Number} minAmount
 */
DynamicType.prototype['minAmount'] = undefined;

/**
 * @member {Number} maxAmount
 */
DynamicType.prototype['maxAmount'] = undefined;






export default DynamicType;

