/**
 * SellPass.WebApi
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import Permissions from './Permissions';

/**
 * The EditPermissionsRequest model module.
 * @module model/EditPermissionsRequest
 * @version v1
 */
class EditPermissionsRequest {
    /**
     * Constructs a new <code>EditPermissionsRequest</code>.
     * @alias module:model/EditPermissionsRequest
     */
    constructor() { 
        
        EditPermissionsRequest.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>EditPermissionsRequest</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/EditPermissionsRequest} obj Optional instance to populate.
     * @return {module:model/EditPermissionsRequest} The populated <code>EditPermissionsRequest</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new EditPermissionsRequest();

            if (data.hasOwnProperty('permissionsList')) {
                obj['permissionsList'] = ApiClient.convertToType(data['permissionsList'], [Permissions]);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>EditPermissionsRequest</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>EditPermissionsRequest</code>.
     */
    static validateJSON(data) {
        // ensure the json data is an array
        if (!Array.isArray(data['permissionsList'])) {
            throw new Error("Expected the field `permissionsList` to be an array in the JSON data but got " + data['permissionsList']);
        }

        return true;
    }


}



/**
 * @member {Array.<module:model/Permissions>} permissionsList
 */
EditPermissionsRequest.prototype['permissionsList'] = undefined;






export default EditPermissionsRequest;

