/**
 * SellPass.WebApi
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The GatewayRules model module.
 * @module model/GatewayRules
 * @version v1
 */
class GatewayRules {
    /**
     * Constructs a new <code>GatewayRules</code>.
     * @alias module:model/GatewayRules
     */
    constructor() { 
        
        GatewayRules.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>GatewayRules</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/GatewayRules} obj Optional instance to populate.
     * @return {module:model/GatewayRules} The populated <code>GatewayRules</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new GatewayRules();

            if (data.hasOwnProperty('blockVpn')) {
                obj['blockVpn'] = ApiClient.convertToType(data['blockVpn'], 'Boolean');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>GatewayRules</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>GatewayRules</code>.
     */
    static validateJSON(data) {

        return true;
    }


}



/**
 * @member {Boolean} blockVpn
 */
GatewayRules.prototype['blockVpn'] = undefined;






export default GatewayRules;

