/**
 * SellPass.WebApi
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import GetProductsPageResponse from './GetProductsPageResponse';

/**
 * The GetProductsPageResponseBaseResponse model module.
 * @module model/GetProductsPageResponseBaseResponse
 * @version v1
 */
class GetProductsPageResponseBaseResponse {
    /**
     * Constructs a new <code>GetProductsPageResponseBaseResponse</code>.
     * @alias module:model/GetProductsPageResponseBaseResponse
     */
    constructor() { 
        
        GetProductsPageResponseBaseResponse.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>GetProductsPageResponseBaseResponse</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/GetProductsPageResponseBaseResponse} obj Optional instance to populate.
     * @return {module:model/GetProductsPageResponseBaseResponse} The populated <code>GetProductsPageResponseBaseResponse</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new GetProductsPageResponseBaseResponse();

            if (data.hasOwnProperty('data')) {
                obj['data'] = GetProductsPageResponse.constructFromObject(data['data']);
            }
            if (data.hasOwnProperty('message')) {
                obj['message'] = ApiClient.convertToType(data['message'], 'String');
            }
            if (data.hasOwnProperty('errors')) {
                obj['errors'] = ApiClient.convertToType(data['errors'], ['String']);
            }
            if (data.hasOwnProperty('log')) {
                obj['log'] = ApiClient.convertToType(data['log'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>GetProductsPageResponseBaseResponse</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>GetProductsPageResponseBaseResponse</code>.
     */
    static validateJSON(data) {
        // validate the optional field `data`
        if (data['data']) { // data not null
          GetProductsPageResponse.validateJSON(data['data']);
        }
        // ensure the json data is a string
        if (data['message'] && !(typeof data['message'] === 'string' || data['message'] instanceof String)) {
            throw new Error("Expected the field `message` to be a primitive type in the JSON string but got " + data['message']);
        }
        // ensure the json data is an array
        if (!Array.isArray(data['errors'])) {
            throw new Error("Expected the field `errors` to be an array in the JSON data but got " + data['errors']);
        }
        // ensure the json data is a string
        if (data['log'] && !(typeof data['log'] === 'string' || data['log'] instanceof String)) {
            throw new Error("Expected the field `log` to be a primitive type in the JSON string but got " + data['log']);
        }

        return true;
    }


}



/**
 * @member {module:model/GetProductsPageResponse} data
 */
GetProductsPageResponseBaseResponse.prototype['data'] = undefined;

/**
 * @member {String} message
 */
GetProductsPageResponseBaseResponse.prototype['message'] = undefined;

/**
 * @member {Array.<String>} errors
 */
GetProductsPageResponseBaseResponse.prototype['errors'] = undefined;

/**
 * @member {String} log
 */
GetProductsPageResponseBaseResponse.prototype['log'] = undefined;






export default GetProductsPageResponseBaseResponse;

