/**
 * SellPass.WebApi
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The GoogleOauthRequest model module.
 * @module model/GoogleOauthRequest
 * @version v1
 */
class GoogleOauthRequest {
    /**
     * Constructs a new <code>GoogleOauthRequest</code>.
     * @alias module:model/GoogleOauthRequest
     * @param code {String} 
     * @param redirectUrl {String} 
     */
    constructor(code, redirectUrl) { 
        
        GoogleOauthRequest.initialize(this, code, redirectUrl);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, code, redirectUrl) { 
        obj['code'] = code;
        obj['redirectUrl'] = redirectUrl;
    }

    /**
     * Constructs a <code>GoogleOauthRequest</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/GoogleOauthRequest} obj Optional instance to populate.
     * @return {module:model/GoogleOauthRequest} The populated <code>GoogleOauthRequest</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new GoogleOauthRequest();

            if (data.hasOwnProperty('code')) {
                obj['code'] = ApiClient.convertToType(data['code'], 'String');
            }
            if (data.hasOwnProperty('redirectUrl')) {
                obj['redirectUrl'] = ApiClient.convertToType(data['redirectUrl'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>GoogleOauthRequest</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>GoogleOauthRequest</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of GoogleOauthRequest.RequiredProperties) {
            if (!data[property]) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['code'] && !(typeof data['code'] === 'string' || data['code'] instanceof String)) {
            throw new Error("Expected the field `code` to be a primitive type in the JSON string but got " + data['code']);
        }
        // ensure the json data is a string
        if (data['redirectUrl'] && !(typeof data['redirectUrl'] === 'string' || data['redirectUrl'] instanceof String)) {
            throw new Error("Expected the field `redirectUrl` to be a primitive type in the JSON string but got " + data['redirectUrl']);
        }

        return true;
    }


}

GoogleOauthRequest.RequiredProperties = ["code", "redirectUrl"];

/**
 * @member {String} code
 */
GoogleOauthRequest.prototype['code'] = undefined;

/**
 * @member {String} redirectUrl
 */
GoogleOauthRequest.prototype['redirectUrl'] = undefined;






export default GoogleOauthRequest;

