/**
 * SellPass.WebApi
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The ModifyListingPosition model module.
 * @module model/ModifyListingPosition
 * @version v1
 */
class ModifyListingPosition {
    /**
     * Constructs a new <code>ModifyListingPosition</code>.
     * @alias module:model/ModifyListingPosition
     */
    constructor() { 
        
        ModifyListingPosition.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>ModifyListingPosition</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/ModifyListingPosition} obj Optional instance to populate.
     * @return {module:model/ModifyListingPosition} The populated <code>ModifyListingPosition</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ModifyListingPosition();

            if (data.hasOwnProperty('listingId')) {
                obj['listingId'] = ApiClient.convertToType(data['listingId'], 'Number');
            }
            if (data.hasOwnProperty('position')) {
                obj['position'] = ApiClient.convertToType(data['position'], 'Number');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>ModifyListingPosition</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>ModifyListingPosition</code>.
     */
    static validateJSON(data) {

        return true;
    }


}



/**
 * @member {Number} listingId
 */
ModifyListingPosition.prototype['listingId'] = undefined;

/**
 * @member {Number} position
 */
ModifyListingPosition.prototype['position'] = undefined;






export default ModifyListingPosition;

