/**
 * SellPass.WebApi
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The PartInvoiceForInvoiceRequest model module.
 * @module model/PartInvoiceForInvoiceRequest
 * @version v1
 */
class PartInvoiceForInvoiceRequest {
    /**
     * Constructs a new <code>PartInvoiceForInvoiceRequest</code>.
     * @alias module:model/PartInvoiceForInvoiceRequest
     * @param productId {Number} 
     * @param productVariantId {Number} 
     * @param quantity {Number} 
     */
    constructor(productId, productVariantId, quantity) { 
        
        PartInvoiceForInvoiceRequest.initialize(this, productId, productVariantId, quantity);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, productId, productVariantId, quantity) { 
        obj['productId'] = productId;
        obj['productVariantId'] = productVariantId;
        obj['quantity'] = quantity;
    }

    /**
     * Constructs a <code>PartInvoiceForInvoiceRequest</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/PartInvoiceForInvoiceRequest} obj Optional instance to populate.
     * @return {module:model/PartInvoiceForInvoiceRequest} The populated <code>PartInvoiceForInvoiceRequest</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new PartInvoiceForInvoiceRequest();

            if (data.hasOwnProperty('productId')) {
                obj['productId'] = ApiClient.convertToType(data['productId'], 'Number');
            }
            if (data.hasOwnProperty('productVariantId')) {
                obj['productVariantId'] = ApiClient.convertToType(data['productVariantId'], 'Number');
            }
            if (data.hasOwnProperty('quantity')) {
                obj['quantity'] = ApiClient.convertToType(data['quantity'], 'Number');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>PartInvoiceForInvoiceRequest</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>PartInvoiceForInvoiceRequest</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of PartInvoiceForInvoiceRequest.RequiredProperties) {
            if (!data[property]) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }

        return true;
    }


}

PartInvoiceForInvoiceRequest.RequiredProperties = ["productId", "productVariantId", "quantity"];

/**
 * @member {Number} productId
 */
PartInvoiceForInvoiceRequest.prototype['productId'] = undefined;

/**
 * @member {Number} productVariantId
 */
PartInvoiceForInvoiceRequest.prototype['productVariantId'] = undefined;

/**
 * @member {Number} quantity
 */
PartInvoiceForInvoiceRequest.prototype['quantity'] = undefined;






export default PartInvoiceForInvoiceRequest;

