/**
 * SellPass.WebApi
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The PostFeedbackRequest model module.
 * @module model/PostFeedbackRequest
 * @version v1
 */
class PostFeedbackRequest {
    /**
     * Constructs a new <code>PostFeedbackRequest</code>.
     * @alias module:model/PostFeedbackRequest
     * @param hash {String} 
     * @param rating {Number} 
     */
    constructor(hash, rating) { 
        
        PostFeedbackRequest.initialize(this, hash, rating);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, hash, rating) { 
        obj['hash'] = hash;
        obj['rating'] = rating;
    }

    /**
     * Constructs a <code>PostFeedbackRequest</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/PostFeedbackRequest} obj Optional instance to populate.
     * @return {module:model/PostFeedbackRequest} The populated <code>PostFeedbackRequest</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new PostFeedbackRequest();

            if (data.hasOwnProperty('hash')) {
                obj['hash'] = ApiClient.convertToType(data['hash'], 'String');
            }
            if (data.hasOwnProperty('rating')) {
                obj['rating'] = ApiClient.convertToType(data['rating'], 'Number');
            }
            if (data.hasOwnProperty('comment')) {
                obj['comment'] = ApiClient.convertToType(data['comment'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>PostFeedbackRequest</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>PostFeedbackRequest</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of PostFeedbackRequest.RequiredProperties) {
            if (!data[property]) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['hash'] && !(typeof data['hash'] === 'string' || data['hash'] instanceof String)) {
            throw new Error("Expected the field `hash` to be a primitive type in the JSON string but got " + data['hash']);
        }
        // ensure the json data is a string
        if (data['comment'] && !(typeof data['comment'] === 'string' || data['comment'] instanceof String)) {
            throw new Error("Expected the field `comment` to be a primitive type in the JSON string but got " + data['comment']);
        }

        return true;
    }


}

PostFeedbackRequest.RequiredProperties = ["hash", "rating"];

/**
 * @member {String} hash
 */
PostFeedbackRequest.prototype['hash'] = undefined;

/**
 * @member {Number} rating
 */
PostFeedbackRequest.prototype['rating'] = undefined;

/**
 * @member {String} comment
 */
PostFeedbackRequest.prototype['comment'] = undefined;






export default PostFeedbackRequest;

