/**
 * SellPass.WebApi
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import StatsForGetShopResponse from './StatsForGetShopResponse';

/**
 * The ProductForListingsData model module.
 * @module model/ProductForListingsData
 * @version v1
 */
class ProductForListingsData {
    /**
     * Constructs a new <code>ProductForListingsData</code>.
     * @alias module:model/ProductForListingsData
     */
    constructor() { 
        
        ProductForListingsData.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>ProductForListingsData</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/ProductForListingsData} obj Optional instance to populate.
     * @return {module:model/ProductForListingsData} The populated <code>ProductForListingsData</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ProductForListingsData();

            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'Number');
            }
            if (data.hasOwnProperty('title')) {
                obj['title'] = ApiClient.convertToType(data['title'], 'String');
            }
            if (data.hasOwnProperty('shortDescription')) {
                obj['shortDescription'] = ApiClient.convertToType(data['shortDescription'], 'String');
            }
            if (data.hasOwnProperty('thumbnailCfImageId')) {
                obj['thumbnailCfImageId'] = ApiClient.convertToType(data['thumbnailCfImageId'], 'String');
            }
            if (data.hasOwnProperty('statistics')) {
                obj['statistics'] = StatsForGetShopResponse.constructFromObject(data['statistics']);
            }
            if (data.hasOwnProperty('groupId')) {
                obj['groupId'] = ApiClient.convertToType(data['groupId'], 'Number');
            }
            if (data.hasOwnProperty('isInstantDelivery')) {
                obj['isInstantDelivery'] = ApiClient.convertToType(data['isInstantDelivery'], 'Boolean');
            }
            if (data.hasOwnProperty('isInStock')) {
                obj['isInStock'] = ApiClient.convertToType(data['isInStock'], 'Boolean');
            }
            if (data.hasOwnProperty('onHold')) {
                obj['onHold'] = ApiClient.convertToType(data['onHold'], 'Boolean');
            }
            if (data.hasOwnProperty('unlisted')) {
                obj['unlisted'] = ApiClient.convertToType(data['unlisted'], 'Boolean');
            }
            if (data.hasOwnProperty('private')) {
                obj['private'] = ApiClient.convertToType(data['private'], 'Boolean');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>ProductForListingsData</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>ProductForListingsData</code>.
     */
    static validateJSON(data) {
        // ensure the json data is a string
        if (data['title'] && !(typeof data['title'] === 'string' || data['title'] instanceof String)) {
            throw new Error("Expected the field `title` to be a primitive type in the JSON string but got " + data['title']);
        }
        // ensure the json data is a string
        if (data['shortDescription'] && !(typeof data['shortDescription'] === 'string' || data['shortDescription'] instanceof String)) {
            throw new Error("Expected the field `shortDescription` to be a primitive type in the JSON string but got " + data['shortDescription']);
        }
        // ensure the json data is a string
        if (data['thumbnailCfImageId'] && !(typeof data['thumbnailCfImageId'] === 'string' || data['thumbnailCfImageId'] instanceof String)) {
            throw new Error("Expected the field `thumbnailCfImageId` to be a primitive type in the JSON string but got " + data['thumbnailCfImageId']);
        }
        // validate the optional field `statistics`
        if (data['statistics']) { // data not null
          StatsForGetShopResponse.validateJSON(data['statistics']);
        }

        return true;
    }


}



/**
 * @member {Number} id
 */
ProductForListingsData.prototype['id'] = undefined;

/**
 * @member {String} title
 */
ProductForListingsData.prototype['title'] = undefined;

/**
 * @member {String} shortDescription
 */
ProductForListingsData.prototype['shortDescription'] = undefined;

/**
 * @member {String} thumbnailCfImageId
 */
ProductForListingsData.prototype['thumbnailCfImageId'] = undefined;

/**
 * @member {module:model/StatsForGetShopResponse} statistics
 */
ProductForListingsData.prototype['statistics'] = undefined;

/**
 * @member {Number} groupId
 */
ProductForListingsData.prototype['groupId'] = undefined;

/**
 * @member {Boolean} isInstantDelivery
 */
ProductForListingsData.prototype['isInstantDelivery'] = undefined;

/**
 * @member {Boolean} isInStock
 */
ProductForListingsData.prototype['isInStock'] = undefined;

/**
 * @member {Boolean} onHold
 */
ProductForListingsData.prototype['onHold'] = undefined;

/**
 * @member {Boolean} unlisted
 */
ProductForListingsData.prototype['unlisted'] = undefined;

/**
 * @member {Boolean} private
 */
ProductForListingsData.prototype['private'] = undefined;






export default ProductForListingsData;

