/**
 * SellPass.WebApi
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import CustomField from './CustomField';
import DiscordSocialConnectSettingsForGetShopResponse from './DiscordSocialConnectSettingsForGetShopResponse';
import DynamicTypeForGetShopResponse from './DynamicTypeForGetShopResponse';
import GatewayForProductResponse from './GatewayForProductResponse';
import PriceData from './PriceData';
import ProductTypes from './ProductTypes';
import SerialsTypeForGetShopResponse from './SerialsTypeForGetShopResponse';
import ServiceTypeForGetShopResponse from './ServiceTypeForGetShopResponse';
import Warranty from './Warranty';

/**
 * The ProductVariantForListingData model module.
 * @module model/ProductVariantForListingData
 * @version v1
 */
class ProductVariantForListingData {
    /**
     * Constructs a new <code>ProductVariantForListingData</code>.
     * @alias module:model/ProductVariantForListingData
     */
    constructor() { 
        
        ProductVariantForListingData.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>ProductVariantForListingData</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/ProductVariantForListingData} obj Optional instance to populate.
     * @return {module:model/ProductVariantForListingData} The populated <code>ProductVariantForListingData</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ProductVariantForListingData();

            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'Number');
            }
            if (data.hasOwnProperty('title')) {
                obj['title'] = ApiClient.convertToType(data['title'], 'String');
            }
            if (data.hasOwnProperty('priceDetails')) {
                obj['priceDetails'] = PriceData.constructFromObject(data['priceDetails']);
            }
            if (data.hasOwnProperty('productType')) {
                obj['productType'] = ProductTypes.constructFromObject(data['productType']);
            }
            if (data.hasOwnProperty('asDynamic')) {
                obj['asDynamic'] = DynamicTypeForGetShopResponse.constructFromObject(data['asDynamic']);
            }
            if (data.hasOwnProperty('asSerials')) {
                obj['asSerials'] = SerialsTypeForGetShopResponse.constructFromObject(data['asSerials']);
            }
            if (data.hasOwnProperty('asService')) {
                obj['asService'] = ServiceTypeForGetShopResponse.constructFromObject(data['asService']);
            }
            if (data.hasOwnProperty('gateways')) {
                obj['gateways'] = ApiClient.convertToType(data['gateways'], [GatewayForProductResponse]);
            }
            if (data.hasOwnProperty('customFields')) {
                obj['customFields'] = ApiClient.convertToType(data['customFields'], [CustomField]);
            }
            if (data.hasOwnProperty('warranty')) {
                obj['warranty'] = Warranty.constructFromObject(data['warranty']);
            }
            if (data.hasOwnProperty('discordSocialConnectSettings')) {
                obj['discordSocialConnectSettings'] = DiscordSocialConnectSettingsForGetShopResponse.constructFromObject(data['discordSocialConnectSettings']);
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>ProductVariantForListingData</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>ProductVariantForListingData</code>.
     */
    static validateJSON(data) {
        // ensure the json data is a string
        if (data['title'] && !(typeof data['title'] === 'string' || data['title'] instanceof String)) {
            throw new Error("Expected the field `title` to be a primitive type in the JSON string but got " + data['title']);
        }
        // validate the optional field `priceDetails`
        if (data['priceDetails']) { // data not null
          PriceData.validateJSON(data['priceDetails']);
        }
        // validate the optional field `asDynamic`
        if (data['asDynamic']) { // data not null
          DynamicTypeForGetShopResponse.validateJSON(data['asDynamic']);
        }
        // validate the optional field `asSerials`
        if (data['asSerials']) { // data not null
          SerialsTypeForGetShopResponse.validateJSON(data['asSerials']);
        }
        // validate the optional field `asService`
        if (data['asService']) { // data not null
          ServiceTypeForGetShopResponse.validateJSON(data['asService']);
        }
        if (data['gateways']) { // data not null
            // ensure the json data is an array
            if (!Array.isArray(data['gateways'])) {
                throw new Error("Expected the field `gateways` to be an array in the JSON data but got " + data['gateways']);
            }
            // validate the optional field `gateways` (array)
            for (const item of data['gateways']) {
                GatewayForProductResponse.validateJsonObject(item);
            };
        }
        if (data['customFields']) { // data not null
            // ensure the json data is an array
            if (!Array.isArray(data['customFields'])) {
                throw new Error("Expected the field `customFields` to be an array in the JSON data but got " + data['customFields']);
            }
            // validate the optional field `customFields` (array)
            for (const item of data['customFields']) {
                CustomField.validateJsonObject(item);
            };
        }
        // validate the optional field `warranty`
        if (data['warranty']) { // data not null
          Warranty.validateJSON(data['warranty']);
        }
        // validate the optional field `discordSocialConnectSettings`
        if (data['discordSocialConnectSettings']) { // data not null
          DiscordSocialConnectSettingsForGetShopResponse.validateJSON(data['discordSocialConnectSettings']);
        }

        return true;
    }


}



/**
 * @member {Number} id
 */
ProductVariantForListingData.prototype['id'] = undefined;

/**
 * @member {String} title
 */
ProductVariantForListingData.prototype['title'] = undefined;

/**
 * @member {module:model/PriceData} priceDetails
 */
ProductVariantForListingData.prototype['priceDetails'] = undefined;

/**
 * @member {module:model/ProductTypes} productType
 */
ProductVariantForListingData.prototype['productType'] = undefined;

/**
 * @member {module:model/DynamicTypeForGetShopResponse} asDynamic
 */
ProductVariantForListingData.prototype['asDynamic'] = undefined;

/**
 * @member {module:model/SerialsTypeForGetShopResponse} asSerials
 */
ProductVariantForListingData.prototype['asSerials'] = undefined;

/**
 * @member {module:model/ServiceTypeForGetShopResponse} asService
 */
ProductVariantForListingData.prototype['asService'] = undefined;

/**
 * @member {Array.<module:model/GatewayForProductResponse>} gateways
 */
ProductVariantForListingData.prototype['gateways'] = undefined;

/**
 * @member {Array.<module:model/CustomField>} customFields
 */
ProductVariantForListingData.prototype['customFields'] = undefined;

/**
 * @member {module:model/Warranty} warranty
 */
ProductVariantForListingData.prototype['warranty'] = undefined;

/**
 * @member {module:model/DiscordSocialConnectSettingsForGetShopResponse} discordSocialConnectSettings
 */
ProductVariantForListingData.prototype['discordSocialConnectSettings'] = undefined;






export default ProductVariantForListingData;

