/**
 * SellPass.WebApi
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The RecheckCashappInvoice model module.
 * @module model/RecheckCashappInvoice
 * @version v1
 */
class RecheckCashappInvoice {
    /**
     * Constructs a new <code>RecheckCashappInvoice</code>.
     * @alias module:model/RecheckCashappInvoice
     * @param transactionId {String} 
     */
    constructor(transactionId) { 
        
        RecheckCashappInvoice.initialize(this, transactionId);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, transactionId) { 
        obj['transactionId'] = transactionId;
    }

    /**
     * Constructs a <code>RecheckCashappInvoice</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/RecheckCashappInvoice} obj Optional instance to populate.
     * @return {module:model/RecheckCashappInvoice} The populated <code>RecheckCashappInvoice</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new RecheckCashappInvoice();

            if (data.hasOwnProperty('transactionId')) {
                obj['transactionId'] = ApiClient.convertToType(data['transactionId'], 'String');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>RecheckCashappInvoice</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>RecheckCashappInvoice</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of RecheckCashappInvoice.RequiredProperties) {
            if (!data[property]) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['transactionId'] && !(typeof data['transactionId'] === 'string' || data['transactionId'] instanceof String)) {
            throw new Error("Expected the field `transactionId` to be a primitive type in the JSON string but got " + data['transactionId']);
        }

        return true;
    }


}

RecheckCashappInvoice.RequiredProperties = ["transactionId"];

/**
 * @member {String} transactionId
 */
RecheckCashappInvoice.prototype['transactionId'] = undefined;






export default RecheckCashappInvoice;

