/**
 * SellPass.WebApi
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The ReplacementRequest model module.
 * @module model/ReplacementRequest
 * @version v1
 */
class ReplacementRequest {
    /**
     * Constructs a new <code>ReplacementRequest</code>.
     * @alias module:model/ReplacementRequest
     * @param partInvoiceId {Number} 
     */
    constructor(partInvoiceId) { 
        
        ReplacementRequest.initialize(this, partInvoiceId);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, partInvoiceId) { 
        obj['partInvoiceId'] = partInvoiceId;
    }

    /**
     * Constructs a <code>ReplacementRequest</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/ReplacementRequest} obj Optional instance to populate.
     * @return {module:model/ReplacementRequest} The populated <code>ReplacementRequest</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ReplacementRequest();

            if (data.hasOwnProperty('partInvoiceId')) {
                obj['partInvoiceId'] = ApiClient.convertToType(data['partInvoiceId'], 'Number');
            }
            if (data.hasOwnProperty('quantity')) {
                obj['quantity'] = ApiClient.convertToType(data['quantity'], 'Number');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>ReplacementRequest</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>ReplacementRequest</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of ReplacementRequest.RequiredProperties) {
            if (!data[property]) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }

        return true;
    }


}

ReplacementRequest.RequiredProperties = ["partInvoiceId"];

/**
 * @member {Number} partInvoiceId
 */
ReplacementRequest.prototype['partInvoiceId'] = undefined;

/**
 * @member {Number} quantity
 */
ReplacementRequest.prototype['quantity'] = undefined;






export default ReplacementRequest;

