/**
 * SellPass.WebApi
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The WarrantyRequest model module.
 * @module model/WarrantyRequest
 * @version v1
 */
class WarrantyRequest {
    /**
     * Constructs a new <code>WarrantyRequest</code>.
     * @alias module:model/WarrantyRequest
     */
    constructor() { 
        
        WarrantyRequest.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>WarrantyRequest</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/WarrantyRequest} obj Optional instance to populate.
     * @return {module:model/WarrantyRequest} The populated <code>WarrantyRequest</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new WarrantyRequest();

            if (data.hasOwnProperty('text')) {
                obj['text'] = ApiClient.convertToType(data['text'], 'String');
            }
            if (data.hasOwnProperty('durationSeconds')) {
                obj['durationSeconds'] = ApiClient.convertToType(data['durationSeconds'], 'Number');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>WarrantyRequest</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>WarrantyRequest</code>.
     */
    static validateJSON(data) {
        // ensure the json data is a string
        if (data['text'] && !(typeof data['text'] === 'string' || data['text'] instanceof String)) {
            throw new Error("Expected the field `text` to be a primitive type in the JSON string but got " + data['text']);
        }

        return true;
    }


}



/**
 * Warranty of the product
 * @member {String} text
 */
WarrantyRequest.prototype['text'] = undefined;

/**
 * Duration of the warranty in seconds
 * @member {Number} durationSeconds
 */
WarrantyRequest.prototype['durationSeconds'] = undefined;






export default WarrantyRequest;

