/**
 * SellPass.WebApi
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */


import ApiClient from "../ApiClient";
import CreateBlockedItemRequest from '../model/CreateBlockedItemRequest';

/**
* Blacklist service.
* @module api/BlacklistApi
* @version v1
*/
export default class BlacklistApi {

    /**
    * Constructs a new BlacklistApi. 
    * @alias module:api/BlacklistApi
    * @class
    * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
    * default to {@link module:ApiClient#instance} if unspecified.
    */
    constructor(apiClient) {
        this.apiClient = apiClient || ApiClient.instance;
    }


    /**
     * Callback function to receive the result of the selfShopIdBlacklistBlockedItemIdDelete operation.
     * @callback module:api/BlacklistApi~selfShopIdBlacklistBlockedItemIdDeleteCallback
     * @param {String} error Error message, if any.
     * @param data This operation does not return a value.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Delete Blocked Item
     * @param {Number} shopId 
     * @param {Number} blockedItemId 
     * @param {module:api/BlacklistApi~selfShopIdBlacklistBlockedItemIdDeleteCallback} callback The callback function, accepting three arguments: error, data, response
     */
    selfShopIdBlacklistBlockedItemIdDelete(shopId, blockedItemId, callback) {
      let postBody = null;
      // verify the required parameter 'shopId' is set
      if (shopId === undefined || shopId === null) {
        throw new Error("Missing the required parameter 'shopId' when calling selfShopIdBlacklistBlockedItemIdDelete");
      }
      // verify the required parameter 'blockedItemId' is set
      if (blockedItemId === undefined || blockedItemId === null) {
        throw new Error("Missing the required parameter 'blockedItemId' when calling selfShopIdBlacklistBlockedItemIdDelete");
      }

      let pathParams = {
        'shopId': shopId,
        'blockedItemId': blockedItemId
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['Bearer'];
      let contentTypes = [];
      let accepts = [];
      let returnType = null;
      return this.apiClient.callApi(
        '/self/{shopId}/blacklist/{blockedItemId}', 'DELETE',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the selfShopIdBlacklistBlockedItemIdGet operation.
     * @callback module:api/BlacklistApi~selfShopIdBlacklistBlockedItemIdGetCallback
     * @param {String} error Error message, if any.
     * @param data This operation does not return a value.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Get Blocked Item
     * @param {Number} shopId 
     * @param {Number} blockedItemId 
     * @param {module:api/BlacklistApi~selfShopIdBlacklistBlockedItemIdGetCallback} callback The callback function, accepting three arguments: error, data, response
     */
    selfShopIdBlacklistBlockedItemIdGet(shopId, blockedItemId, callback) {
      let postBody = null;
      // verify the required parameter 'shopId' is set
      if (shopId === undefined || shopId === null) {
        throw new Error("Missing the required parameter 'shopId' when calling selfShopIdBlacklistBlockedItemIdGet");
      }
      // verify the required parameter 'blockedItemId' is set
      if (blockedItemId === undefined || blockedItemId === null) {
        throw new Error("Missing the required parameter 'blockedItemId' when calling selfShopIdBlacklistBlockedItemIdGet");
      }

      let pathParams = {
        'shopId': shopId,
        'blockedItemId': blockedItemId
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['Bearer'];
      let contentTypes = [];
      let accepts = [];
      let returnType = null;
      return this.apiClient.callApi(
        '/self/{shopId}/blacklist/{blockedItemId}', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the selfShopIdBlacklistBlockedItemIdPut operation.
     * @callback module:api/BlacklistApi~selfShopIdBlacklistBlockedItemIdPutCallback
     * @param {String} error Error message, if any.
     * @param data This operation does not return a value.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Edit Blocked Item
     * @param {Number} shopId 
     * @param {Number} blockedItemId 
     * @param {Object} opts Optional parameters
     * @param {module:model/CreateBlockedItemRequest} opts.createBlockedItemRequest 
     * @param {module:api/BlacklistApi~selfShopIdBlacklistBlockedItemIdPutCallback} callback The callback function, accepting three arguments: error, data, response
     */
    selfShopIdBlacklistBlockedItemIdPut(shopId, blockedItemId, opts, callback) {
      opts = opts || {};
      let postBody = opts['createBlockedItemRequest'];
      // verify the required parameter 'shopId' is set
      if (shopId === undefined || shopId === null) {
        throw new Error("Missing the required parameter 'shopId' when calling selfShopIdBlacklistBlockedItemIdPut");
      }
      // verify the required parameter 'blockedItemId' is set
      if (blockedItemId === undefined || blockedItemId === null) {
        throw new Error("Missing the required parameter 'blockedItemId' when calling selfShopIdBlacklistBlockedItemIdPut");
      }

      let pathParams = {
        'shopId': shopId,
        'blockedItemId': blockedItemId
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['Bearer'];
      let contentTypes = ['application/json', 'text/json', 'application/*+json'];
      let accepts = [];
      let returnType = null;
      return this.apiClient.callApi(
        '/self/{shopId}/blacklist/{blockedItemId}', 'PUT',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the selfShopIdBlacklistGet operation.
     * @callback module:api/BlacklistApi~selfShopIdBlacklistGetCallback
     * @param {String} error Error message, if any.
     * @param data This operation does not return a value.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Get All
     * @param {Number} shopId 
     * @param {Object} opts Optional parameters
     * @param {Number} opts.pageNumber 
     * @param {Number} opts.pageSize 
     * @param {String} opts.searchString 
     * @param {module:api/BlacklistApi~selfShopIdBlacklistGetCallback} callback The callback function, accepting three arguments: error, data, response
     */
    selfShopIdBlacklistGet(shopId, opts, callback) {
      opts = opts || {};
      let postBody = null;
      // verify the required parameter 'shopId' is set
      if (shopId === undefined || shopId === null) {
        throw new Error("Missing the required parameter 'shopId' when calling selfShopIdBlacklistGet");
      }

      let pathParams = {
        'shopId': shopId
      };
      let queryParams = {
        'PageNumber': opts['pageNumber'],
        'PageSize': opts['pageSize'],
        'searchString': opts['searchString']
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['Bearer'];
      let contentTypes = [];
      let accepts = [];
      let returnType = null;
      return this.apiClient.callApi(
        '/self/{shopId}/blacklist', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the selfShopIdBlacklistPost operation.
     * @callback module:api/BlacklistApi~selfShopIdBlacklistPostCallback
     * @param {String} error Error message, if any.
     * @param data This operation does not return a value.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Create Blocked Item
     * @param {Number} shopId 
     * @param {Object} opts Optional parameters
     * @param {module:model/CreateBlockedItemRequest} opts.createBlockedItemRequest 
     * @param {module:api/BlacklistApi~selfShopIdBlacklistPostCallback} callback The callback function, accepting three arguments: error, data, response
     */
    selfShopIdBlacklistPost(shopId, opts, callback) {
      opts = opts || {};
      let postBody = opts['createBlockedItemRequest'];
      // verify the required parameter 'shopId' is set
      if (shopId === undefined || shopId === null) {
        throw new Error("Missing the required parameter 'shopId' when calling selfShopIdBlacklistPost");
      }

      let pathParams = {
        'shopId': shopId
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['Bearer'];
      let contentTypes = ['application/json', 'text/json', 'application/*+json'];
      let accepts = [];
      let returnType = null;
      return this.apiClient.callApi(
        '/self/{shopId}/blacklist', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }


}
