/**
 * SellPass.WebApi
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.SellPassWebApi);
  }
}(this, function(expect, SellPassWebApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new SellPassWebApi.CreateProductV2Variant();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('CreateProductV2Variant', function() {
    it('should create an instance of CreateProductV2Variant', function() {
      // uncomment below and update the code to test CreateProductV2Variant
      //var instance = new SellPassWebApi.CreateProductV2Variant();
      //expect(instance).to.be.a(SellPassWebApi.CreateProductV2Variant);
    });

    it('should have the property id (base name: "id")', function() {
      // uncomment below and update the code to test the property id
      //var instance = new SellPassWebApi.CreateProductV2Variant();
      //expect(instance).to.be();
    });

    it('should have the property title (base name: "title")', function() {
      // uncomment below and update the code to test the property title
      //var instance = new SellPassWebApi.CreateProductV2Variant();
      //expect(instance).to.be();
    });

    it('should have the property description (base name: "description")', function() {
      // uncomment below and update the code to test the property description
      //var instance = new SellPassWebApi.CreateProductV2Variant();
      //expect(instance).to.be();
    });

    it('should have the property priceDetails (base name: "priceDetails")', function() {
      // uncomment below and update the code to test the property priceDetails
      //var instance = new SellPassWebApi.CreateProductV2Variant();
      //expect(instance).to.be();
    });

    it('should have the property gateways (base name: "gateways")', function() {
      // uncomment below and update the code to test the property gateways
      //var instance = new SellPassWebApi.CreateProductV2Variant();
      //expect(instance).to.be();
    });

    it('should have the property productType (base name: "productType")', function() {
      // uncomment below and update the code to test the property productType
      //var instance = new SellPassWebApi.CreateProductV2Variant();
      //expect(instance).to.be();
    });

    it('should have the property asDynamic (base name: "asDynamic")', function() {
      // uncomment below and update the code to test the property asDynamic
      //var instance = new SellPassWebApi.CreateProductV2Variant();
      //expect(instance).to.be();
    });

    it('should have the property asSerials (base name: "asSerials")', function() {
      // uncomment below and update the code to test the property asSerials
      //var instance = new SellPassWebApi.CreateProductV2Variant();
      //expect(instance).to.be();
    });

    it('should have the property asService (base name: "asService")', function() {
      // uncomment below and update the code to test the property asService
      //var instance = new SellPassWebApi.CreateProductV2Variant();
      //expect(instance).to.be();
    });

    it('should have the property customerNote (base name: "customerNote")', function() {
      // uncomment below and update the code to test the property customerNote
      //var instance = new SellPassWebApi.CreateProductV2Variant();
      //expect(instance).to.be();
    });

    it('should have the property redirectUrl (base name: "redirectUrl")', function() {
      // uncomment below and update the code to test the property redirectUrl
      //var instance = new SellPassWebApi.CreateProductV2Variant();
      //expect(instance).to.be();
    });

    it('should have the property customFields (base name: "customFields")', function() {
      // uncomment below and update the code to test the property customFields
      //var instance = new SellPassWebApi.CreateProductV2Variant();
      //expect(instance).to.be();
    });

    it('should have the property warranty (base name: "warranty")', function() {
      // uncomment below and update the code to test the property warranty
      //var instance = new SellPassWebApi.CreateProductV2Variant();
      //expect(instance).to.be();
    });

    it('should have the property discordSocialConnectSettings (base name: "discordSocialConnectSettings")', function() {
      // uncomment below and update the code to test the property discordSocialConnectSettings
      //var instance = new SellPassWebApi.CreateProductV2Variant();
      //expect(instance).to.be();
    });

  });

}));
