/**
 * SellPass.WebApi
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.SellPassWebApi);
  }
}(this, function(expect, SellPassWebApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new SellPassWebApi.CreateCouponRequest();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('CreateCouponRequest', function() {
    it('should create an instance of CreateCouponRequest', function() {
      // uncomment below and update the code to test CreateCouponRequest
      //var instance = new SellPassWebApi.CreateCouponRequest();
      //expect(instance).to.be.a(SellPassWebApi.CreateCouponRequest);
    });

    it('should have the property name (base name: "name")', function() {
      // uncomment below and update the code to test the property name
      //var instance = new SellPassWebApi.CreateCouponRequest();
      //expect(instance).to.be();
    });

    it('should have the property note (base name: "note")', function() {
      // uncomment below and update the code to test the property note
      //var instance = new SellPassWebApi.CreateCouponRequest();
      //expect(instance).to.be();
    });

    it('should have the property discount (base name: "discount")', function() {
      // uncomment below and update the code to test the property discount
      //var instance = new SellPassWebApi.CreateCouponRequest();
      //expect(instance).to.be();
    });

    it('should have the property isFixed (base name: "isFixed")', function() {
      // uncomment below and update the code to test the property isFixed
      //var instance = new SellPassWebApi.CreateCouponRequest();
      //expect(instance).to.be();
    });

    it('should have the property startDate (base name: "startDate")', function() {
      // uncomment below and update the code to test the property startDate
      //var instance = new SellPassWebApi.CreateCouponRequest();
      //expect(instance).to.be();
    });

    it('should have the property endDate (base name: "endDate")', function() {
      // uncomment below and update the code to test the property endDate
      //var instance = new SellPassWebApi.CreateCouponRequest();
      //expect(instance).to.be();
    });

    it('should have the property restrictToProducts (base name: "restrictToProducts")', function() {
      // uncomment below and update the code to test the property restrictToProducts
      //var instance = new SellPassWebApi.CreateCouponRequest();
      //expect(instance).to.be();
    });

    it('should have the property restrictToGateways (base name: "restrictToGateways")', function() {
      // uncomment below and update the code to test the property restrictToGateways
      //var instance = new SellPassWebApi.CreateCouponRequest();
      //expect(instance).to.be();
    });

    it('should have the property maxUses (base name: "maxUses")', function() {
      // uncomment below and update the code to test the property maxUses
      //var instance = new SellPassWebApi.CreateCouponRequest();
      //expect(instance).to.be();
    });

  });

}));
