/**
 * SellPass.WebApi
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.SellPassWebApi);
  }
}(this, function(expect, SellPassWebApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new SellPassWebApi.GetMainDetailsResponse();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('GetMainDetailsResponse', function() {
    it('should create an instance of GetMainDetailsResponse', function() {
      // uncomment below and update the code to test GetMainDetailsResponse
      //var instance = new SellPassWebApi.GetMainDetailsResponse();
      //expect(instance).to.be.a(SellPassWebApi.GetMainDetailsResponse);
    });

    it('should have the property shop (base name: "shop")', function() {
      // uncomment below and update the code to test the property shop
      //var instance = new SellPassWebApi.GetMainDetailsResponse();
      //expect(instance).to.be();
    });

    it('should have the property feedbacks (base name: "feedbacks")', function() {
      // uncomment below and update the code to test the property feedbacks
      //var instance = new SellPassWebApi.GetMainDetailsResponse();
      //expect(instance).to.be();
    });

    it('should have the property announcements (base name: "announcements")', function() {
      // uncomment below and update the code to test the property announcements
      //var instance = new SellPassWebApi.GetMainDetailsResponse();
      //expect(instance).to.be();
    });

    it('should have the property listings (base name: "listings")', function() {
      // uncomment below and update the code to test the property listings
      //var instance = new SellPassWebApi.GetMainDetailsResponse();
      //expect(instance).to.be();
    });

    it('should have the property categories (base name: "categories")', function() {
      // uncomment below and update the code to test the property categories
      //var instance = new SellPassWebApi.GetMainDetailsResponse();
      //expect(instance).to.be();
    });

  });

}));
