/**
 * SellPass.WebApi
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.SellPassWebApi);
  }
}(this, function(expect, SellPassWebApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new SellPassWebApi.ListingData();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('ListingData', function() {
    it('should create an instance of ListingData', function() {
      // uncomment below and update the code to test ListingData
      //var instance = new SellPassWebApi.ListingData();
      //expect(instance).to.be.a(SellPassWebApi.ListingData);
    });

    it('should have the property id (base name: "id")', function() {
      // uncomment below and update the code to test the property id
      //var instance = new SellPassWebApi.ListingData();
      //expect(instance).to.be();
    });

    it('should have the property path (base name: "path")', function() {
      // uncomment below and update the code to test the property path
      //var instance = new SellPassWebApi.ListingData();
      //expect(instance).to.be();
    });

    it('should have the property searchWordsMeta (base name: "searchWordsMeta")', function() {
      // uncomment below and update the code to test the property searchWordsMeta
      //var instance = new SellPassWebApi.ListingData();
      //expect(instance).to.be();
    });

    it('should have the property position (base name: "position")', function() {
      // uncomment below and update the code to test the property position
      //var instance = new SellPassWebApi.ListingData();
      //expect(instance).to.be();
    });

    it('should have the property minPriceDetails (base name: "minPriceDetails")', function() {
      // uncomment below and update the code to test the property minPriceDetails
      //var instance = new SellPassWebApi.ListingData();
      //expect(instance).to.be();
    });

    it('should have the property seo (base name: "seo")', function() {
      // uncomment below and update the code to test the property seo
      //var instance = new SellPassWebApi.ListingData();
      //expect(instance).to.be();
    });

    it('should have the property visibility (base name: "visibility")', function() {
      // uncomment below and update the code to test the property visibility
      //var instance = new SellPassWebApi.ListingData();
      //expect(instance).to.be();
    });

    it('should have the property type (base name: "type")', function() {
      // uncomment below and update the code to test the property type
      //var instance = new SellPassWebApi.ListingData();
      //expect(instance).to.be();
    });

    it('should have the property product (base name: "product")', function() {
      // uncomment below and update the code to test the property product
      //var instance = new SellPassWebApi.ListingData();
      //expect(instance).to.be();
    });

    it('should have the property group (base name: "group")', function() {
      // uncomment below and update the code to test the property group
      //var instance = new SellPassWebApi.ListingData();
      //expect(instance).to.be();
    });

  });

}));
