/**
 * SellPass.WebApi
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.SellPassWebApi);
  }
}(this, function(expect, SellPassWebApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new SellPassWebApi.RegisterUserBasicRequest();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('RegisterUserBasicRequest', function() {
    it('should create an instance of RegisterUserBasicRequest', function() {
      // uncomment below and update the code to test RegisterUserBasicRequest
      //var instance = new SellPassWebApi.RegisterUserBasicRequest();
      //expect(instance).to.be.a(SellPassWebApi.RegisterUserBasicRequest);
    });

    it('should have the property refer (base name: "refer")', function() {
      // uncomment below and update the code to test the property refer
      //var instance = new SellPassWebApi.RegisterUserBasicRequest();
      //expect(instance).to.be();
    });

    it('should have the property email (base name: "email")', function() {
      // uncomment below and update the code to test the property email
      //var instance = new SellPassWebApi.RegisterUserBasicRequest();
      //expect(instance).to.be();
    });

    it('should have the property password (base name: "password")', function() {
      // uncomment below and update the code to test the property password
      //var instance = new SellPassWebApi.RegisterUserBasicRequest();
      //expect(instance).to.be();
    });

    it('should have the property recaptcha (base name: "recaptcha")', function() {
      // uncomment below and update the code to test the property recaptcha
      //var instance = new SellPassWebApi.RegisterUserBasicRequest();
      //expect(instance).to.be();
    });

  });

}));
