/**
 * SellPass.WebApi
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.SellPassWebApi);
  }
}(this, function(expect, SellPassWebApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new SellPassWebApi.BlacklistApi();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('BlacklistApi', function() {
    describe('selfShopIdBlacklistBlockedItemIdDelete', function() {
      it('should call selfShopIdBlacklistBlockedItemIdDelete successfully', function(done) {
        //uncomment below and update the code to test selfShopIdBlacklistBlockedItemIdDelete
        //instance.selfShopIdBlacklistBlockedItemIdDelete(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('selfShopIdBlacklistBlockedItemIdGet', function() {
      it('should call selfShopIdBlacklistBlockedItemIdGet successfully', function(done) {
        //uncomment below and update the code to test selfShopIdBlacklistBlockedItemIdGet
        //instance.selfShopIdBlacklistBlockedItemIdGet(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('selfShopIdBlacklistBlockedItemIdPut', function() {
      it('should call selfShopIdBlacklistBlockedItemIdPut successfully', function(done) {
        //uncomment below and update the code to test selfShopIdBlacklistBlockedItemIdPut
        //instance.selfShopIdBlacklistBlockedItemIdPut(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('selfShopIdBlacklistGet', function() {
      it('should call selfShopIdBlacklistGet successfully', function(done) {
        //uncomment below and update the code to test selfShopIdBlacklistGet
        //instance.selfShopIdBlacklistGet(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('selfShopIdBlacklistPost', function() {
      it('should call selfShopIdBlacklistPost successfully', function(done) {
        //uncomment below and update the code to test selfShopIdBlacklistPost
        //instance.selfShopIdBlacklistPost(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
  });

}));
