/**
 * SellPass.WebApi
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.SellPassWebApi);
  }
}(this, function(expect, SellPassWebApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new SellPassWebApi.CouponsApi();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('CouponsApi', function() {
    describe('selfShopIdCouponsCouponIdDelete', function() {
      it('should call selfShopIdCouponsCouponIdDelete successfully', function(done) {
        //uncomment below and update the code to test selfShopIdCouponsCouponIdDelete
        //instance.selfShopIdCouponsCouponIdDelete(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('selfShopIdCouponsCouponIdGet', function() {
      it('should call selfShopIdCouponsCouponIdGet successfully', function(done) {
        //uncomment below and update the code to test selfShopIdCouponsCouponIdGet
        //instance.selfShopIdCouponsCouponIdGet(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('selfShopIdCouponsCouponIdPut', function() {
      it('should call selfShopIdCouponsCouponIdPut successfully', function(done) {
        //uncomment below and update the code to test selfShopIdCouponsCouponIdPut
        //instance.selfShopIdCouponsCouponIdPut(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('selfShopIdCouponsGet', function() {
      it('should call selfShopIdCouponsGet successfully', function(done) {
        //uncomment below and update the code to test selfShopIdCouponsGet
        //instance.selfShopIdCouponsGet(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('selfShopIdCouponsPost', function() {
      it('should call selfShopIdCouponsPost successfully', function(done) {
        //uncomment below and update the code to test selfShopIdCouponsPost
        //instance.selfShopIdCouponsPost(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
  });

}));
