/**
 * SellPass.WebApi
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.SellPassWebApi);
  }
}(this, function(expect, SellPassWebApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new SellPassWebApi.CustomizationApi();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('CustomizationApi', function() {
    describe('selfShopIdCustomizationDesignPut', function() {
      it('should call selfShopIdCustomizationDesignPut successfully', function(done) {
        //uncomment below and update the code to test selfShopIdCustomizationDesignPut
        //instance.selfShopIdCustomizationDesignPut(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('selfShopIdCustomizationGet', function() {
      it('should call selfShopIdCustomizationGet successfully', function(done) {
        //uncomment below and update the code to test selfShopIdCustomizationGet
        //instance.selfShopIdCustomizationGet(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('selfShopIdCustomizationLinksPut', function() {
      it('should call selfShopIdCustomizationLinksPut successfully', function(done) {
        //uncomment below and update the code to test selfShopIdCustomizationLinksPut
        //instance.selfShopIdCustomizationLinksPut(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('selfShopIdCustomizationLogoPost', function() {
      it('should call selfShopIdCustomizationLogoPost successfully', function(done) {
        //uncomment below and update the code to test selfShopIdCustomizationLogoPost
        //instance.selfShopIdCustomizationLogoPost(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('selfShopIdCustomizationSeoFaviconPost', function() {
      it('should call selfShopIdCustomizationSeoFaviconPost successfully', function(done) {
        //uncomment below and update the code to test selfShopIdCustomizationSeoFaviconPost
        //instance.selfShopIdCustomizationSeoFaviconPost(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('selfShopIdCustomizationSeoImagePost', function() {
      it('should call selfShopIdCustomizationSeoImagePost successfully', function(done) {
        //uncomment below and update the code to test selfShopIdCustomizationSeoImagePost
        //instance.selfShopIdCustomizationSeoImagePost(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('selfShopIdCustomizationSeoPut', function() {
      it('should call selfShopIdCustomizationSeoPut successfully', function(done) {
        //uncomment below and update the code to test selfShopIdCustomizationSeoPut
        //instance.selfShopIdCustomizationSeoPut(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('selfShopIdCustomizationStorefrontBackgroundPost', function() {
      it('should call selfShopIdCustomizationStorefrontBackgroundPost successfully', function(done) {
        //uncomment below and update the code to test selfShopIdCustomizationStorefrontBackgroundPost
        //instance.selfShopIdCustomizationStorefrontBackgroundPost(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('selfShopIdCustomizationStorefrontPut', function() {
      it('should call selfShopIdCustomizationStorefrontPut successfully', function(done) {
        //uncomment below and update the code to test selfShopIdCustomizationStorefrontPut
        //instance.selfShopIdCustomizationStorefrontPut(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('selfShopIdCustomizationWidgetsPut', function() {
      it('should call selfShopIdCustomizationWidgetsPut successfully', function(done) {
        //uncomment below and update the code to test selfShopIdCustomizationWidgetsPut
        //instance.selfShopIdCustomizationWidgetsPut(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
  });

}));
