/**
 * SellPass.WebApi
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.SellPassWebApi);
  }
}(this, function(expect, SellPassWebApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new SellPassWebApi.OrdersApi();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('OrdersApi', function() {
    describe('selfShopIdInvoicesGet', function() {
      it('should call selfShopIdInvoicesGet successfully', function(done) {
        //uncomment below and update the code to test selfShopIdInvoicesGet
        //instance.selfShopIdInvoicesGet(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('selfShopIdInvoicesInvoiceIdGet', function() {
      it('should call selfShopIdInvoicesInvoiceIdGet successfully', function(done) {
        //uncomment below and update the code to test selfShopIdInvoicesInvoiceIdGet
        //instance.selfShopIdInvoicesInvoiceIdGet(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('selfShopIdInvoicesInvoiceIdProcessPost', function() {
      it('should call selfShopIdInvoicesInvoiceIdProcessPost successfully', function(done) {
        //uncomment below and update the code to test selfShopIdInvoicesInvoiceIdProcessPost
        //instance.selfShopIdInvoicesInvoiceIdProcessPost(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('selfShopIdInvoicesInvoiceIdReplacementPost', function() {
      it('should call selfShopIdInvoicesInvoiceIdReplacementPost successfully', function(done) {
        //uncomment below and update the code to test selfShopIdInvoicesInvoiceIdReplacementPost
        //instance.selfShopIdInvoicesInvoiceIdReplacementPost(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('selfShopIdInvoicesInvoiceIdResendPost', function() {
      it('should call selfShopIdInvoicesInvoiceIdResendPost successfully', function(done) {
        //uncomment below and update the code to test selfShopIdInvoicesInvoiceIdResendPost
        //instance.selfShopIdInvoicesInvoiceIdResendPost(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
  });

}));
