/**
 * SellPass.WebApi
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.SellPassWebApi);
  }
}(this, function(expect, SellPassWebApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new SellPassWebApi.PaymentsShopSettingsApi();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('PaymentsShopSettingsApi', function() {
    describe('selfShopIdSettingsPaymentsCashappPut', function() {
      it('should call selfShopIdSettingsPaymentsCashappPut successfully', function(done) {
        //uncomment below and update the code to test selfShopIdSettingsPaymentsCashappPut
        //instance.selfShopIdSettingsPaymentsCashappPut(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('selfShopIdSettingsPaymentsCoinbasecommercePut', function() {
      it('should call selfShopIdSettingsPaymentsCoinbasecommercePut successfully', function(done) {
        //uncomment below and update the code to test selfShopIdSettingsPaymentsCoinbasecommercePut
        //instance.selfShopIdSettingsPaymentsCoinbasecommercePut(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('selfShopIdSettingsPaymentsPaypalFfPut', function() {
      it('should call selfShopIdSettingsPaymentsPaypalFfPut successfully', function(done) {
        //uncomment below and update the code to test selfShopIdSettingsPaymentsPaypalFfPut
        //instance.selfShopIdSettingsPaymentsPaypalFfPut(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('selfShopIdSettingsPaymentsPaypalemailPut', function() {
      it('should call selfShopIdSettingsPaymentsPaypalemailPut successfully', function(done) {
        //uncomment below and update the code to test selfShopIdSettingsPaymentsPaypalemailPut
        //instance.selfShopIdSettingsPaymentsPaypalemailPut(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('selfShopIdSettingsPaymentsStripeconnectPut', function() {
      it('should call selfShopIdSettingsPaymentsStripeconnectPut successfully', function(done) {
        //uncomment below and update the code to test selfShopIdSettingsPaymentsStripeconnectPut
        //instance.selfShopIdSettingsPaymentsStripeconnectPut(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('selfShopIdSettingsPaymentsVirtualPaymentsPut', function() {
      it('should call selfShopIdSettingsPaymentsVirtualPaymentsPut successfully', function(done) {
        //uncomment below and update the code to test selfShopIdSettingsPaymentsVirtualPaymentsPut
        //instance.selfShopIdSettingsPaymentsVirtualPaymentsPut(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
  });

}));
