/**
 * SellPass.WebApi
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.SellPassWebApi);
  }
}(this, function(expect, SellPassWebApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new SellPassWebApi.PublicPageInfoApi();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('PublicPageInfoApi', function() {
    describe('v2PublicShopsShopIdAnnouncementsAnnouncementPathGet', function() {
      it('should call v2PublicShopsShopIdAnnouncementsAnnouncementPathGet successfully', function(done) {
        //uncomment below and update the code to test v2PublicShopsShopIdAnnouncementsAnnouncementPathGet
        //instance.v2PublicShopsShopIdAnnouncementsAnnouncementPathGet(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('v2PublicShopsShopIdFaqsGet', function() {
      it('should call v2PublicShopsShopIdFaqsGet successfully', function(done) {
        //uncomment below and update the code to test v2PublicShopsShopIdFaqsGet
        //instance.v2PublicShopsShopIdFaqsGet(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('v2PublicShopsShopIdFeedbacksGet', function() {
      it('should call v2PublicShopsShopIdFeedbacksGet successfully', function(done) {
        //uncomment below and update the code to test v2PublicShopsShopIdFeedbacksGet
        //instance.v2PublicShopsShopIdFeedbacksGet(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('v2PublicShopsShopIdListingsGet', function() {
      it('should call v2PublicShopsShopIdListingsGet successfully', function(done) {
        //uncomment below and update the code to test v2PublicShopsShopIdListingsGet
        //instance.v2PublicShopsShopIdListingsGet(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('v2PublicShopsShopIdListingsListingPathGet', function() {
      it('should call v2PublicShopsShopIdListingsListingPathGet successfully', function(done) {
        //uncomment below and update the code to test v2PublicShopsShopIdListingsListingPathGet
        //instance.v2PublicShopsShopIdListingsListingPathGet(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('v2PublicShopsShopIdMainGet', function() {
      it('should call v2PublicShopsShopIdMainGet successfully', function(done) {
        //uncomment below and update the code to test v2PublicShopsShopIdMainGet
        //instance.v2PublicShopsShopIdMainGet(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
  });

}));
