/**
 * SellPass.WebApi
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.SellPassWebApi);
  }
}(this, function(expect, SellPassWebApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new SellPassWebApi.TicketsApi();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('TicketsApi', function() {
    describe('selfShopIdTicketsGet', function() {
      it('should call selfShopIdTicketsGet successfully', function(done) {
        //uncomment below and update the code to test selfShopIdTicketsGet
        //instance.selfShopIdTicketsGet(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('selfShopIdTicketsTicketIdClosePost', function() {
      it('should call selfShopIdTicketsTicketIdClosePost successfully', function(done) {
        //uncomment below and update the code to test selfShopIdTicketsTicketIdClosePost
        //instance.selfShopIdTicketsTicketIdClosePost(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('selfShopIdTicketsTicketIdGet', function() {
      it('should call selfShopIdTicketsTicketIdGet successfully', function(done) {
        //uncomment below and update the code to test selfShopIdTicketsTicketIdGet
        //instance.selfShopIdTicketsTicketIdGet(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('selfShopIdTicketsTicketIdMessagePost', function() {
      it('should call selfShopIdTicketsTicketIdMessagePost successfully', function(done) {
        //uncomment below and update the code to test selfShopIdTicketsTicketIdMessagePost
        //instance.selfShopIdTicketsTicketIdMessagePost(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
  });

}));
